[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder, default

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.0.4
    crankyoldgit/IRremoteESP8266 @ ^2.8.6

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D MONITOR_BAUD_RATE=115200
    -D FIRMWARE_VERSION=\"0.1.0-alpha\"
    -D DEVICE_MODEL=\"AzureEssence-SmartAC\"
    -D DHT_PIN=13
    -D DHT_TYPE=DHT22
    -D IR_RX_PIN=14
    -D IR_TX_PIN=25
    -D IR_OBSTACLE_PIN=26
    -D PRESENCE_PIN=26
    -D PRESENCE_ACTIVE_LOW=false
    -D HAS_PRESENCE_SENSOR=true
    -D HAS_IR_TRANSMITTER=true
    -D STATUS_LED_PIN=2
